on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5,17 * * 2,4'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Runs a single command using the runners shell
      - - uses: actions/setup-node@v3
    with:
      node-version: "16"
    env:
      GITHUB_TOKEN: ${{ secrets.TESTING_GITHUB_TOKEN }}
  - run: npm config set package-lock true
  - run: echo 'package-lock=true'>> .npmrc
  - run: npm install -g npm@latest
  - run: npm i -g npm-upgrade
 
      # Runs a single command using the runners shell
      - name: Install HostlistCompiler
        run: npm install hostlist-compiler

      # Runs a set of commands using the runners shell
      - name: Build Adguard list
        run: hostlist-compiler -c configuration.json -o Adguardstylepc.txt
